# Generated by Django 4.2.18 on 2025-01-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_productvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='age',
            field=models.CharField(blank=True, choices=[('adult', 'Adult'), ('kids', 'Kids')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='style',
            field=models.CharField(blank=True, choices=[('casual', 'Casual'), ('formal', 'Formal'), ('sport', 'Sport')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='type',
            field=models.CharField(blank=True, choices=[('shirt', 'Shirt'), ('pants', 'Pants'), ('jacket', 'Jacket')], max_length=20, null=True),
        ),
    ]
