# Generated by Django 4.2.18 on 2025-01-24 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_productvariant_age_alter_productvariant_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'Extra-Extra-Small'), ('XS', 'Extra-Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra-Extra Large'), ('A0', 'A0'), ('A1', 'A1'), ('A1L', 'A1L'), ('A2', 'A2'), ('A2L', 'A2L'), ('A3', 'A3'), ('A3L', 'A3L'), ('A4', 'A4'), ('F0', 'F0'), ('F1', 'F1'), ('F2', 'F2'), ('F3', 'F3'), ('F4', 'F4'), ('M000', 'M000'), ('M00', 'M00'), ('M0', 'M0'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3'), ('M4', 'M4')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='style',
            field=models.CharField(blank=True, choices=[('ap', 'Apparel'), ('ac', 'Accessories'), ('gi', 'Gi'), ('ng', 'Nogi')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='type',
            field=models.CharField(blank=True, choices=[('gi', 'Gi'), ('rg', 'Rashguard'), ('dk', 'Shorts'), ('ck', 'Spats'), ('bt', 'Belt'), ('te', 'Tee'), ('cn', 'Crewneck'), ('ho', 'Hoodie'), ('bo', 'Bottle'), ('tr', 'Trousers'), ('ft', 'Finger Tape'), ('br', 'Bra'), ('bg', 'Bag'), ('jk', 'Jacket')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('sold_quantity', models.IntegerField()),
                ('return_quantity', models.IntegerField(blank=True, null=True)),
                ('sold_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('return_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='inventory.productvariant')),
            ],
        ),
    ]
