# Generated by Django 4.2.18 on 2025-01-24 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventorysnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(default=datetime.date.today, verbose_name='Order Date')),
                ('invoice_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice ID')),
                ('invoice', models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Invoice File')),
            ],
        ),
    ]
