# Generated by Django 4.2.18 on 2025-01-24 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity Ordered')),
                ('item_cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost Price (CNY)')),
                ('date_expected', models.DateField(verbose_name='Expected Arrival Date')),
                ('date_arrived', models.DateField(blank=True, null=True, verbose_name='Actual Arrival Date')),
                ('actual_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Actual Quantity Arrived')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='inventory.order', verbose_name='Related Order')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='inventory.productvariant', verbose_name='Product Variant')),
            ],
        ),
    ]
