# Generated by Django 4.2.18 on 2025-03-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['-variant_code']},
        ),
        migrations.AddField(
            model_name='product',
            name='decommissioned',
            field=models.BooleanField(default=False, help_text='Select if this product is old and retired.'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, choices=[('XXS', 'Extra-Extra-Small'), ('XS', 'Extra-Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra-Extra Large'), ('A0', 'A0'), ('A1', 'A1'), ('A1L', 'A1L'), ('A2', 'A2'), ('A2L', 'A2L'), ('A3', 'A3'), ('A3L', 'A3L'), ('A4', 'A4'), ('F0', 'F0'), ('F1', 'F1'), ('F2', 'F2'), ('F3', 'F3'), ('F4', 'F4'), ('M000', 'M000'), ('M00', 'M00'), ('M0', 'M0'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3'), ('M4', 'M4')], max_length=4, null=True),
        ),
    ]
