# Generated by Django 4.2.18 on 2025-03-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_productvariant_options_product_decommissioned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_photos/'),
        ),
    ]
