# Generated by Django 4.2.18 on 2025-03-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_product_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounted',
            field=models.BooleanField(default=False, help_text='Check if this product is currently discounted.'),
        ),
    ]
