# Generated by Django 4.2.18 on 2025-05-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_product_discounted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Recommended retail price.', max_digits=10, null=True),
        ),
    ]
