# Generated by Django 4.2.18 on 2025-05-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_product_retail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='order_number',
            field=models.CharField(db_index=True, default=1234567, max_length=50),
            preserve_default=False,
        ),
    ]
