# Generated by Django 4.2.18 on 2025-07-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_sale_order_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-order_date"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["product_id"]},
        ),
    ]
