# Generated by Django 5.2.4 on 2025-07-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_group_series_product_groups_product_series"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="age",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="style",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="type",
        ),
        migrations.AddField(
            model_name="product",
            name="age",
            field=models.CharField(
                blank=True,
                choices=[("adult", "Adult"), ("kids", "Kids")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ap", "Apparel"),
                    ("ac", "Accessories"),
                    ("gi", "Gi"),
                    ("ng", "Nogi"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gi", "Gi"),
                    ("rg", "Rashguard"),
                    ("dk", "Shorts"),
                    ("ck", "Spats"),
                    ("bt", "Belt"),
                    ("te", "Tee"),
                    ("cn", "Crewneck"),
                    ("ho", "Hoodie"),
                    ("bo", "Bottle"),
                    ("tr", "Trousers"),
                    ("ft", "Finger Tape"),
                    ("br", "Bra"),
                    ("bg", "Bag"),
                    ("jk", "Jacket"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
