# Generated by Django 5.2.4 on 2025-07-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_remove_productvariant_age_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestockSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="restock_settings",
                        to="inventory.group",
                    ),
                ),
            ],
        ),
    ]
