# Generated by Django 4.2.18 on 2025-07-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_restocksetting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorysnapshot",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="date_arrived",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="Actual Arrival Date"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="date_expected",
            field=models.DateField(db_index=True, verbose_name="Expected Arrival Date"),
        ),
        migrations.AlterField(
            model_name="sale",
            name="date",
            field=models.DateField(db_index=True),
        ),
    ]
